### ISSUE TITLE
[RFP] Name for the tool

### ISSUE THREAD

**Issue by siddharth-krishna** [etsap-TIMES/xl2times#109]
`times-excel-reader` is a bit unwieldy and perhaps doesn't capture the purpose and scope of the tool accurately. We invite proposals and feedback!

Some suggestions to start the ball rolling:
- `tidi` for `TImes Data Ingester` or `TImes Data Interpreter` 
- `tida` for `TImes Data Analyser` (though we don't really do too much analysis..)

**Comment by olejandro** [comment]
@ggiannakidis @pedodds @jamesglynn @markusblesl @lippkaufelix @panosev @sophiechlela @willcattoneeca

**Comment by pedodds** [comment]
I quite like the original times-excel-reader - I understand what it does from the name.

I don't have a good alternative.  Maybe "Community interpretater for TIMES models (CITE)"?

**Comment by panosev** [comment]
I would prefer a name that provides straightforward information about what the tool is doing and what purpose is. 

Since it provides a flexible interface to convert VEDA EXCEL-format files to another format, e.g., flat text files. suitable for GAMS my suggestion is something like "TIMES XLS to DD Converter"  or simply TIMES XL2DD tool. Yes, I am very bad at finding names for tools :-)

**Comment by samwebster** [comment]
From my limited knowledge of the TIMES project, it seems that whilst the input format of this tool is relatively fixed, the output format could change if the model is translated to another language. Would avoiding using GAMS or DD in the name make it more future-proof?
________________________________

**Comment by panosev** [comment]
What about, a simpler name like "Excel to TIMES" or XL2TIMES, that does not bound to specific language and data format, other than that the source of data should be EXCEL ?

**Comment by akanudia** [comment]
The "~ tags" that are being interpreted in this project are the original contribution of **Veda**, and they have **no direct relationship with TIMES**. The same data formats produce input for MARKAL in older versions of Veda, and they will be used to prepare input for other models in future.

So, the Excel files that are being read are Veda-TIMES files. Calling them TIMES excel files gives the false impression that ~FI* and ~TFM* tags are TIMES concepts.

https://veda-documentation.readthedocs.io/en/latest/

**Comment by akanudia** [comment]
Community Interpreter of Veda-TIMES Models (CIVE) ?

**Comment by gagdad2** [comment]
I want to re-enforce the point Amit is making. The design of the VEDA TIMES templates is something that arose from the knowledge, skills and innovation residing with KanORS. Not only do I feel that this needs to be acknowledged in the name of this new tool, but such credit for the "tags" concept for handling TIMES input data in a dynamic flexible manner needs to be properly credited to KanORS in the documentation. So "VEDA" must appear someplace in name at the very least seems to me. 

With that said consider variants along the lines of what Amit suggests above or perhaps Veda-TIMES Template Interpreter.

**Comment by GargiuloM** [comment]
Gary's suggested name, VEDA-TIMES Template Interpreter, works well in my opinion and I also agree that the word VEDA should be used in the name for consistency with the approach taken. Also, even the trainings provided by ETSAP are called VEDA-TIMES trainings, considering that the main focus is how to build and/or use a TIMES model built in VEDA.

**Comment by LippkauFelix** [comment]
I like the proposal of Amit a lot. Community Interpreter for Veda-TIMES Models is easy to understand. Among the 3 given abbreviations I like CIVE the most (but what is the "E" for?)

**Comment by akanudia** [comment]
> I like the proposal of Amit a lot. Community Interpreter for Veda-TIMES Models is easy to understand. Among the 3 given abbreviations I like CIVE the most (but what is the "E" for?)

Just borrowing a vowel from "Veda-TIMES" - to make it pronounceable.

**Comment by olejandro** [comment]
Great discussion so far. Please keep it coming!
Some things that we as developers would like to make sure and will impact the choice:
- the name should be available on PyPi;
- the name should not limit the functionality of the tool (e.g. with respect to possible inputs / outputs);
- the name should communicate the focus on TIMES

**Comment by gagdad2** [comment]
@Olegandro, I think you are missing the point. The use of the ~tags enabling the flexibility of the VEDA TIMES templates needs to be explicitly acknowledged. It really is the intellectual property of KanORS, which Amit is willing to "share" but with due credit given for it.

**Comment by akanudia** [comment]
Won't the reference to TIMES have a similar contradiction? Like I already said, the generic syntax you are reading can serve any RES-based model. In fact, this tool could be even more effective for models that do not have an evolved interface at this point.

And the "Veda way" you refer to is quite deep. You have to compare with ANSWER for that. You could possibly evolve the "Veda way" in this project, but I don't see how you can move away from it.

**Comment by Antti-L** [comment]
Veda does also have a general meaning, "knowledge" (from Sanskrit) , and so it would be suitable regardless of the input formats supported.  :-)

**Comment by olejandro** [comment]
Appologies if the "Veda way" was perceived negatively. There was no intention from me to for it to sound that way!

**Comment by olejandro** [comment]
> @olejandro, I think you are missing the point. The use of the ~tags enabling the flexibility of the VEDA TIMES templates needs to be explicitly acknowledged. It really is the intellectual property of KanORS, which Amit is willing to "share" but with due credit given for it.

Thanks for sharing you opinion @gagdad2. I don't have any issue acknowledging "Veda input format for TIMES models". However I see the functionality of the tool going beyond this input format.

**Comment by gagdad2** [comment]
But you still plan on employing the ~tag & highly flexible table configuration concepts, right. Those are the brainchild of Amit, & including VEDA in the name of this ETSAP sponsored R&D undertaking seems to me to be a good idea to acknowledge that explicitly,

**Comment by olejandro** [comment]
Thanks again @gagdad2! If you ask me, I think there are better / more appropriate ways of acknowledging Amit's contribution.

**Comment by gagdad2** [comment]
it's not simply about that, he's requested said acknowledgement & deserves it.

**Comment by olejandro** [comment]
thanks @gagdad2 for expressing your opinion and concern. The purpose of this issue is to collect ideas for the naming of the tool. Based on the ideas collected and a suitability check (e.g. the name should be available on PyPi), we'll make a poll to find a name appealing to the community.

**Comment by akanudia** [comment]
> This project is an open source tool to convert TIMES model Excel input files to DD format ready for processing by GAMS. The intention is to make it easier for people to reproduce research results on TIMES models.

These statements ignore the **existence** of Veda - it is **subsumed** in TIMES. I just want to ensure that developers and users of this project are aware that Veda and TIMES are separate entities.

"TIMES model input files" are the DD files. The Excel files you are refering to are **Veda input files**. These Excel files contain an original syntax that introduced a new way of **creating** data - via rule-based processing of flexible formats. For example, the ability to identify nodes of a RES based on set membership, name, description, and topology and add/edit parameters - is Veda. This has absolutely nothing to do with TIMES. The project is replicating this ability using different software tools, without mentioning "Veda" anywhere, which implicitly makes all the data concepts of Veda a part of TIMES.

**Comment by olejandro** [comment]
Thanks @akanudia. I have opened a separate issue to update the project description.

**Comment by akanudia** [comment]
That's a great idea @olejandro. Actually, I have no interest in influencing the name of this tool. I mainly want the description to be factually correct and for it to be written with non-ETSAP audience in mind.

**Comment by siddharth-krishna** [comment]
Thank you all for your comments. Please vote for the new name of the tool on this google form:
https://forms.gle/JPa4tv2RzgijqgJE8

(The form requires signing into a Google account. Email addresses are only used to ensure no duplicate or spam votes. All emails will be deleted when the poll is resolved on Wed 22 Nov.)

The shortlist includes all names suggested above that met the criteria and that were not already taken on [PyPI](https://pypi.org/).

**Comment by siddharth-krishna** [comment]
Hi everyone,

The poll has been concluded, and the new name of the tool is `xl2times`. The URL to the GitHub repo has changed to:
https://github.com/etsap-TIMES/xl2times

It will soon be available to install via pip (`pip install xl2times` or https://pypi.org/project/xl2times/). The full results were:

![image](https://github.com/etsap-TIMES/xl2times/assets/10712637/f288798d-456c-46d3-b729-f22aaa8450a1)

Thank you all for your feedback.
