### ISSUE TITLE
Create a TimesModelData class

### ISSUE THREAD

**Issue by olejandro** [etsap-TIMES/xl2times#11]
One thing I'm wondering, perhaps for later: Because of the order of code in the PR diff, I thought that there was an input table called `VedaProcessSets` and started searching for it in the Veda documentation Part IV! I only later realized we're using it as a means to pass meta information from one transform to another. If we find ourselves doing this again, it might be cleaner to create a class called `TimesModelData` or something that encapsulates both the `List[EmbeddedXlTable]` as well as any meta information / context. So this will change the type of every transform in `transform_list` to be `TimesModelData -> TimesModelData`, and that way it's clearer what things like `VedaProcessSets` are. What do you think?

_Originally posted by @siddharth-krishna in https://github.com/samwebster/times-excel-reader/pull/8#pullrequestreview-1301461313_

**Comment by olejandro** [comment]
Reletated to #9

**Comment by olejandro** [comment]
Related #41

**Comment by siddharth-krishna** [comment]
I can think of two ways of doing this:

### 1. `TimesModelData` class containing all transforms as methods
Create a class `TimesModelData` whose attributes contain both contextual information (such as the information in `times-info.json`) as well as an attribute `tables` that contains the list/dict of DataFrames.

Make all the transforms as methods of this class. This means they will have access to the attributes, including the context and the main tables data, and will modify them in place. For example:
```python
class TimesModelData:
    def __init__(self, input_files, times_info_file):
        self.tables = extract_tables(input_files, in_parallel=True)
        self.times_info = read_times_info(times_info_file)

    def process_user_constraint_tables(self):
        for table in tables:
            # This is a helper method that processes each table, using context / configurations
            # like self.times_info if necessary:
            process_user_constraint_table(table)

    def convert_excel_to_times(self):
        # This method runs all the transfoms in order:
        transforms = [ ..., process_user_constraint_tables, ...]
        for tranform in transforms:
            ...
```

### 2. Every transform takes a `Config` class object as first argument
We create a new class called something like `Config` or `TimesContext` that contains all the contextual information or configuration. We then modify every transform into a method that takes as first argument a `Config` object. We then modify the `convert_excel_to_times` method to pass the config to each transform.
```python
class Config:
    category: Dict[str, Category]
    mappings: List[datatypes.TimesXlMap]
    ...

    def __init__(self, mapping_fname, info_fname):
        self.category = process_info_file(info_fname)
        self.mappings = read_mappings(mapping)

# Transforms look like this now:
def process_user_constraint_tables(
    config: Config,
    tables: List[datatypes.EmbeddedXlTable],
) -> List[datatypes.EmbeddedXlTable]:
    ...

# And convert_excel_to_times is modified like so:
    config = Config("times_mapping.txt", "times-info.json", ...)
    transform_list = [...]
    input = raw_tables
    output = {}
    for transform in transform_list:
        start_time = time.time()
        output = transform(config, input)
        end_time = time.time()
        input = output
```

**Comment by olejandro** [comment]
@siddharth-krishna I believe we are ready to transition to using `TIMESModelData` class. I am thinking it could have the following properties (working list):
- data (what `times_mapping.txt` refers to as `~FI_T` currently)
- processes (what `times_mapping.txt` refers to as `~FI_Process` currently)
- commodities (what `times_mapping.txt` refers to as `~FI_Comm` currently)
- regions
- period_definitions
- timeslice_definitions
- etc...

I guess, some of them would be dataframes, while others lists, etc?
