### ISSUE TITLE
Resolve issue with latest openpyxl

### ISSUE THREAD

**Issue by samwebster** [etsap-TIMES/xl2times#14]
See https://github.com/samwebster/times-excel-reader/commit/8adc5b0e3f61858f4b271fa4a939264e394d1949

**Comment by olejandro** [comment]
Seems to be working with v3.1.1
Maybe a bug got fixed? https://openpyxl.readthedocs.io/en/stable/changes.html

**Comment by olejandro** [comment]
@samwebster

**Comment by samwebster** [comment]
Problem still seems to be there - https://github.com/samwebster/times-excel-reader/actions/runs/4276711710/jobs/7445005244

**Comment by olejandro** [comment]
Seems to be this issue: https://foss.heptapod.net/openpyxl/openpyxl/-/issues/1967
