### ISSUE TITLE
Support user-defined external regions

### ISSUE THREAD

**Issue by olejandro** [etsap-TIMES/xl2times#162]
Regarding external regions, we currently add `IMPEXP` and `MINRNW` to `ALL_REG`. Is there anything else we should be adding?

_Originally posted by @olejandro in https://github.com/etsap-TIMES/xl2times/issues/161#issuecomment-1893825697_

**Comment by Antti-L** [comment]
Yes there definitely is!   Please see comments in https://github.com/etsap-TIMES/xl2times/pull/161#issuecomment-1893841778  and below.

**Comment by olejandro** [comment]
Here is an example `~BookRegions_Map` table based on our discussion in #161:

| BookName | Region |
| --- | --- |
|      |  R1 |
| W | R2 |
|      | R3 |
| N  | R4 |
|     | R5 |

@Antti-L, assuming there is a workbook `VT_W_*` and there is no workbook `VT_N_*`, should the following be true:
- `REG` contains `R2` and `R3`
- `ALL_REG` contains `R1`, `R2`, `R3`, `R4` and `R5`

**Comment by Antti-L** [comment]
I don't think you can ever leave `BookName` blank.  So, I think your example is erroneous (first row does not have a `BookName` at all).  For the other blanks, `BookName` is inherited from above (as is usual).  If we would exclude the erroneus first row, then yes, only R2 and R3 would be internal regions, and R4 and R5 would be external.

**Comment by olejandro** [comment]
> I don't think you can ever leave `BookName` blank. So, I think your example is erroneous (first row does not have a `BookName` at all).

Ok, so this is something to check. In my view, this makes much more sense than using a `BookName` pattern that doesn't exist to define external regions, because one can't distinguish it from a simple typo. In any case, we could think of messages to inform the user of what's going on.

**Comment by Antti-L** [comment]
Well, it seems you don't fully appreciate the original functionality.  It works very well if you have several books, and you want to experiment with a small subset of regions out of those in the full model:  You just need to exclude the base templates for the excluded regions, and VEDA automatically makes the excluded regions external. No need to edit SysSettings at all, nor other model templates if you have prepared the model well.  But yes, I agree that accepting blanks as well could be considered reasonable for adding external regions.

**Comment by olejandro** [comment]
Well, maybe I do... In your example, what's the benefit of adding the regions from the deleted files to external regions over not having them at all?

**Comment by Antti-L** [comment]
All the trade links to/from the external regions.  They would not work if the external regions do not exist...
