### ISSUE TITLE
Case insensitive comparison when determining correct rows

### ISSUE THREAD

**Issue by olejandro** [etsap-TIMES/xl2times#182]
@siddharth-krishna any chance we could do case insensitive comparison when determining correct rows in the CI?

Currently there is a regression in #181 on Ireland due to `NATIONAL` vs `National` in `ALL_REG`. GAMS is case insensitive in this respect...

**Comment by siddharth-krishna** [comment]
Yes, shouldn't be a problem. Are all columns case insensitive, or does GAMS care about case in certain places?

**Comment by olejandro** [comment]
Yes, all are case insensitive.

**Comment by olejandro** [comment]
@siddharth-krishna any chance you could take a look at this? E.g., `UNITS_COM` should not have neither additional, nor missing records on Ireland.

**Comment by olejandro** [comment]
Fixed in #255
