### ISSUE TITLE
Very small differences in numerical values when determining correct rows

### ISSUE THREAD

**Issue by olejandro** [etsap-TIMES/xl2times#246]
E.g., there are currently 24 additional / missing values for `PRC_RESID` on Ireland.

**Comment by olejandro** [comment]
@siddharth-krishna any chance you could take a look at this one?

**Comment by olejandro** [comment]
> I assume you mean the additional rows in https://github.com/etsap-TIMES/xl2times/actions/runs/11969575511/job/33370600563?pr=240 for commit https://github.com/etsap-TIMES/xl2times/commit/5e9db3e3fde5ee45f3f2230bd3b707a106caa624

Well, they are identified both as additional and missing. :-)

**Comment by olejandro** [comment]
> Perhaps it's time to look into this again and see if we can remove convert_to_string, ensure we're using correct column types (int for years, float for other numeric tables, etc) and then compare DataFrames with a tolerance value?

How about doing this in a step-wise manner? Most of the columns are ok to stay strings. We could start with e.g. `value` (the most important one) and then see whether we should do it for `year`.

**Comment by siddharth-krishna** [comment]
I had another idea for a quicker/step-wise solution: we could print floats as strings to a specific precision in `convert_to_string`, which might fix the issue for now, and then continue with the correct column types in a separate PR?

**Comment by siddharth-krishna** [comment]
I'm closing this because #252 introduced an epsilon for comparing numeric values, and the larger goal of using correct pandas data types can be tracked by #47. Let me know if I'm missing something.
