### ISSUE TITLE
Processing rules in TODO need to be updated

### ISSUE THREAD

**Issue by samwebster** [etsap-TIMES/xl2times#3]
See https://github.com/microsoft/times-excel-reader/issues/18

**Comment by olejandro** [comment]
Should we move the rules out of the TODO? Would be nice to have them only in one place...

**Comment by samwebster** [comment]
I think so. It would be great if we could introduce enough helper methods that the code is concise enough to become the 'doc'. No idea if that's realistic

**Comment by olejandro** [comment]
TODO has been removed in #202
