### ISSUE TITLE
Support MIG tables

### ISSUE THREAD

**Issue by olejandro** [etsap-TIMES/xl2times#83]

**Comment by olejandro** [comment]
@siddharth-krishna would you be up for this one? 😄

**Comment by siddharth-krishna** [comment]
Sure! Could you give me some pointers on the details of the task? Should I look at times doc part 4? Thanks

**Comment by olejandro** [comment]
Unfortunatelly, I don't think there is much there...
Basically, it works as a kind of a combinaton of the `UPD` / `INS` variants, i.e. the value is obtained as `UPD`, but it's added as `INS` with some of its properties changed. For example, in the following table an existing `year1` value is multiplied by 0.9 and is inserted as `year2`.

| Attribute | Year1 | Year2 | SourceScen | AllRegions | Pset_PN |
| --- | --- | --- | --- |  --- | --- |
| NCAP_COST | 2020 | 2030 | ELC_EIA_AEO2022 | *0.9 | E_NUC*01 |

**Comment by olejandro** [comment]
Know columns for this table type include `attribute2`, `commodity2`, etc. To be able to generalise table processing, if empty, I think, values for those fields should be filled using `attribute`, `commodity`, etc.

**Comment by siddharth-krishna** [comment]
Thanks. I'll take a crack at it!

**Comment by siddharth-krishna** [comment]
In Demo 4, we have this MIG table that has a `year2` column but no `year`. Does this mean we just insert the value `5` for year `0` (i.e. if we have no `year` value then `year2` cannot be written in terms of it, e.g. `*0.9`).

```
sheetname: Interpol_Extrapol_Defaults
range: B4:G6
filename: benchmarks/xlsx/DemoS_004/SysSettings.xlsx
tag: ~TFM_MIG
types: LimType (object), Attribute (object), Year2 (object), AllRegions (object), Pset_PN (object)
LimType,Attribute,Year2,AllRegions,Pset_PN
UP,ACT_BND,0,5,
```

Also, would the output data be the same if we replaced the `TFM_MIG` table above with the following `TFM_UPD` one? Perhaps one way to implement MIG tables is to reduce them to UPD tables that have the same result?

```
tag: ~TFM_UPD
LimType,Attribute,Year,AllRegions,Pset_PN
UP,ACT_BND,0,5,*
```

**Comment by olejandro** [comment]
> (i.e. if we have no `year` value then `year2` cannot be written in terms of it, e.g. `*0.9`)

Unless not having `year` means `any/every` year for which attribute is present... `*0.9` then becomes problematic in case multiple records are present (i.e. how to assign them to a single `year2`)? However, since in our case there is just `5` (i.e. no multiplication), there would not be any ambiguity.  

The example of an `TFM_UPD` table would/should not work, because it requires a pre-existing record with `year=0`. A `TFM_INS` on the other hand would work. However, compared to `TFM_MIG`, it would create a record with `year=0` even if there is no data for any other years specified.

**Comment by olejandro** [comment]
There is some discussion on specifying interpolation settings in Veda 2.0 (and how it is different from Veda-FE) [here](https://forum.kanors-emr.org/showthread.php?tid=1297&pid=6816&highlight=interpolation+rule#pid6816)
